In [138]:
import numpy as np

In [ ]:
# NUmpy Stands for Numerical python and is the core library for numeric and scientific computing

In [4]:
n1 = np.array([10,20,30,40])

In [6]:
l1 = [1,2,3,4]

In [7]:
n2 = np.array(l1)

In [8]:
n1 + n2

array([11, 22, 33, 44])

In [11]:
n3 = np.array([[1,2,3,4],[1,2,3,4]])

In [12]:
n3

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [15]:
# initialize empty

In [17]:
n4 = np.zeros((1,2))

In [19]:
n4

array([[0., 0.]])

In [21]:
n5 = np.zeros((5,5))

In [23]:
n5

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
n6 = np.full((3,4),7)

In [28]:
n6

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [29]:
# arange

In [30]:
n7 = np.arange(10,20)

In [32]:
n7

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [34]:
n8 = np.arange(10,20,2)

In [35]:
n8

array([10, 12, 14, 16, 18])

In [36]:
# random initalize

In [43]:
n9 = np.random.randint(1,100,5)

In [45]:
n9

array([93, 50, 40, 98, 25])

In [46]:
# reshare

In [52]:
n10 = np.array([[1,2,3,4],[1,2,3,4]])

In [53]:
n10

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [56]:
n10.shape = (4,2)

In [58]:
n10

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [59]:
# array join, vstack, hstack, column_stack

In [61]:
n11= np.array([10,20,30])
n12 = np.array([40,50,60])

In [63]:
n13vstack = np.vstack((n11,n12))

In [65]:
n13vstack

array([[10, 20, 30],
       [40, 50, 60]])

In [69]:
n13hstack= np.hstack((n11,n12))

In [71]:
n13hstack

array([10, 20, 30, 40, 50, 60])

In [77]:
n13column_stack = np.column_stack((n11,n12))

In [78]:
n13column_stack

array([[10, 40],
       [20, 50],
       [30, 60]])

In [76]:
# intersection and difference

In [86]:
n14 = np.array([10,20,30,40,50,60])
n15 = np.array([50,60,70,80])

In [88]:
np.intersect1d(n14,n15)

array([50, 60])

In [90]:
np.setdiff1d(n14,n15)

array([10, 20, 30, 40])

In [94]:
np.setdiff1d(n15,n14)

array([70, 80])

In [95]:
# adding array

In [97]:
n16 = np.array([1,2])
n17 = np.array([3,4])

In [100]:
np.sum([n16,n17])

10

In [102]:
np.sum([n16,n17],axis=0)

array([4, 6])

In [104]:
np.sum([n16,n17],axis=1)

array([3, 7])

In [105]:
# Basic addition, multiplication, subtraction, division

In [113]:
n18 = np.array([10,20,30])

In [116]:
n18 = n18+1 #### *,-,/

In [117]:
n18

array([12, 22, 32])

In [118]:
# mean, sd, median

In [120]:
n19 = np.random.randint(1,20,5)

In [122]:
n19

array([ 6, 14,  8,  2,  8])

In [124]:
np.mean(n19)

7.6

In [126]:
np.std(n19)

3.8781438859330635

In [128]:
np.median(n19)

8.0

In [129]:
# save & load

In [131]:
n20 = np.array([10,20,30,40,50,])

In [133]:
np.save('my_numpy',n20)

In [136]:
n21 = np.load('my_numpy.npy')

In [137]:
n21

array([10, 20, 30, 40, 50])