In [61]:
import tensorflow as tf

In [62]:
tf.__version__

'2.3.0'

In [63]:
# Tensorflow doesnot normalize the data, we need to use sklearn to Normalized it.
from sklearn.preprocessing import Normalizer

In [64]:
# Load data
(train_x,train_y),(_,_) = tf.keras.datasets.boston_housing.load_data(test_split=0)

In [65]:
train_x.shape

(506, 13)

In [66]:
train_y.shape

(506,)

In [67]:
# Tensorflow uses 32 by default
train_x = train_x.astype('float32')
train_y = train_y.astype('float32')

In [68]:
transformer = Normalizer()
train_x = transformer.fit_transform(train_x)

In [69]:
train_x[0]

array([0.0024119 , 0.        , 0.01592969, 0.        , 0.00105285,
       0.01201967, 0.17945358, 0.00778265, 0.00782786, 0.60078794,
       0.04109624, 0.776719  , 0.03663436], dtype=float32)

In [76]:
# We are initializing weights and Bias with Zero
w = tf.zeros(shape=(13,1))
b = tf.zeros(shape=(1))
w

<tf.Tensor: shape=(13, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)>

In [71]:
def prediction (x,w,b):
    xw_matmul = tf.matmul(x,w)
    y = tf.add(xw_matmul, b)
    return y

In [72]:
def loss(y_actual,y_predicted):
    diff = y_actual = y_predicted
    sqr = tf.square(diff)
    avg = tf.reduce_mean(sqr)
    return avg

## Function to train the Model
1. Record all the mathematical steps to calculate Loss. We will record the steps using Gradient Tape
2. Calculate Gradients of Loss w.r.t weights and bias
3. Update Weights and bias based in gradients and learing rate.

In [73]:
def train(x, y_actual, w, b, learning_rate=0.01):
    # Record mathematical operations on 'tape' to calculate loss
    with tf.GradientTape() as t:
        t.watch([w,b])
        
        current_prediction = prediction(x,w,b)
        current_loss = loss(y_actual, current_prediction)
    
    # Calculate Gradients for Loss with respect to Weights and Bias
    dw,db = t.gradient(current_loss,[w,b])
    
    # Update Weights and Bias
    w = w - learning_rate*dw
    b = b - learning_rate*db
    
    return w,b

# Start Training

In [74]:
# Train for 100 Times
for i in range(20):
    w, b = train(train_x, train_y, w, b)
    print('Current Loss in iteration', i, loss(train_y, prediction(train_x,w,b)).numpy())

Current Loss in iteration 0 0.0
Current Loss in iteration 1 0.0
Current Loss in iteration 2 0.0
Current Loss in iteration 3 0.0
Current Loss in iteration 4 0.0
Current Loss in iteration 5 0.0
Current Loss in iteration 6 0.0
Current Loss in iteration 7 0.0
Current Loss in iteration 8 0.0
Current Loss in iteration 9 0.0
Current Loss in iteration 10 0.0
Current Loss in iteration 11 0.0
Current Loss in iteration 12 0.0
Current Loss in iteration 13 0.0
Current Loss in iteration 14 0.0
Current Loss in iteration 15 0.0
Current Loss in iteration 16 0.0
Current Loss in iteration 17 0.0
Current Loss in iteration 18 0.0
Current Loss in iteration 19 0.0


In [75]:
train_x[0]

array([0.0024119 , 0.        , 0.01592969, 0.        , 0.00105285,
       0.01201967, 0.17945358, 0.00778265, 0.00782786, 0.60078794,
       0.04109624, 0.776719  , 0.03663436], dtype=float32)